name: Selenium VNExpress Scraper

on:
  schedule:
    - cron: '*/3 * * * *'
  workflow_dispatch:
  push:
    branches: [master]

jobs:
  run-selenium:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Install Chrome & Chromedriver
        run: |
          sudo apt update
          sudo apt install -y wget unzip curl

          wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
          sudo dpkg -i google-chrome*.deb || sudo apt -f install -y
          CHROME_VERSION=$(google-chrome --version | grep -oP '\d+\.\d+\.\d+\.\d+')
          echo "Installed Chrome version: $CHROME_VERSION"

          BASE_URL="https://storage.googleapis.com/chrome-for-testing-public"
          wget -O chromedriver.zip "${BASE_URL}/${CHROME_VERSION}/linux64/chromedriver-linux64.zip"
          unzip chromedriver.zip
          sudo mv chromedriver-linux64/chromedriver /usr/local/bin/
          sudo chmod +x /usr/local/bin/chromedriver

      - name: Install mongosh
        run: |
          curl -fsSL https://pgp.mongodb.com/server-6.0.asc |
            gpg --dearmor -o /usr/share/keyrings/mongodb-server-6.0.gpg
          echo "deb [ signed-by=/usr/share/keyrings/mongodb-server-6.0.gpg ] https://repo.mongodb.org/apt/ubuntu focal/mongodb-org/6.0 multiverse" | \
            sudo tee /etc/apt/sources.list.d/mongodb-org-6.0.list
          sudo apt-get update
          sudo apt-get install -y mongodb-mongosh

      - name: Run scraper
        run: python index.py

      - name: Verify inserted MongoDB documents
        run: |
          echo "Checking if documents are inserted..."
          echo "db.${MONGO_COLLECTION}.find().limit(1).pretty()" | mongosh "${MONGO_URI}${MONGO_DB}"
        env:
          MONGO_URI: mongodb+srv://dangtoi:12345@topic.g8zzie1.mongodb.net/
          MONGO_DB: vnexpress
          MONGO_COLLECTION: news
